### ISSUE TITLE
Make sure all commit are singed by GPG key

### ISSUE THREAD

**Issue by MiteshShah** [AnsiPress/AnsiPress#11]

**Comment by MiteshShah** [comment]
@harshadyeola If possible put Github related files under .github directiory
Refer - https://github.com/EasyEngine/easyengine/tree/master/.github

**Comment by harshadyeola** [comment]
@MiteshShah 
do you have any idea to implement how do we enforce users to push commits verifies with his GPG keys?
I can only setup release scripts for us that will easy our release cycle and make sure that the tags will be signed with GPG key?

**Comment by MiteshShah** [comment]
@harshadyeola No idea but if we can do for tags then its also good :)

**Comment by harshadyeola** [comment]
cool I will start working then. I will make use of git-flow for our release cycle. my scripts will take care of release. cc @MiteshShah @gau1991
