### ISSUE TITLE
Setup NTP, PS1, & disable ssh password logins

### ISSUE THREAD

**Issue by harshadyeola** [AnsiPress/AnsiPress#14]
Setup that on Bootstrap roles.

**Comment by MiteshShah** [comment]
@harshadyeola @gau1991 If we disable password login for SSH then we first have to copy user keys on server.

For that if user does not have any ssh keys in that case what do you suggest here ?

**Comment by harshadyeola** [comment]
@MiteshShah I think we have agreed on not disabling ssh password logins.
We should leave this to user.

**Comment by MiteshShah** [comment]
Okay So we just need NTP and PS1 now to close this issue :)
