### ISSUE TITLE
Add support for ubuntu 17.04

### ISSUE THREAD

**Issue by asm0dey** [AnsiPress/AnsiPress#38]
Right now AnsiPress gives exception because something cant be found in opensuse repo

**Comment by MiteshShah** [comment]
@asm0dey I'd never built NGINX package for Ubuntu 17.04.

TBH - Right now me and @harshadyeola both are busy and not able to find time for the AnsiPress project.

Right now my 1st priority is 

- Support all latest for Ubuntu LTS
- Support Debian 9 LTS 

So mostly we never built package for distro which does had LTS tag.
