### ISSUE TITLE
 [WARNING]: provided hosts list is empty, only localhost is available

### ISSUE THREAD

**Issue by nithinsai** [AnsiPress/AnsiPress#40]
PLAY [Welcome to AnsiPress Setup] **********************************************
skipping: no hosts matched

**Comment by nithinsai** [comment]
[WARNING]: provided hosts list is empty, only localhost is available

ERROR! 'host' is not a valid attribute for a Play

The error appears to have been in '/home/mac/1324b9a86305e6cf2d86db2d86bcb5e4/AnsiPress/setup.yml': line 2, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

---
- name: Welcome to AnsiPress Setup
  ^ here
[1] After Adding IP as Host
[2]Using Google Cloud-Ubuntu 16.04

**Comment by MiteshShah** [comment]
Refer Docs - https://ansipress.gitbooks.io/docs/
